### PR TITLE
Change sorting so that it works with Python 3.x too

### PR DESCRIPTION
**Pull request by rwvo**
Change sorting so that it not only works with Python 2.7, but with 3.x too.
Without the modification, running with Python 3.x results in an error:

```
Traceback (most recent call last):
  File "/opt/rocm/bin/tblextr.py", line 120, in <module>
    ret = print_tbl(outfile)                         
  File "/opt/rocm/bin/tblextr.py", line 90, in print_tbl
    keys.sort(key=int)                                                          
AttributeError: 'dict_keys' object has no attribute 'sort'                   
```

### CODE REVIEW

**Review by eshcherb — APPROVED** [review]

**Comment by eshcherb** [comment]
LGTM to me
